import type { Metadata } from "next";
import "../legal.css";

export const metadata: Metadata = {
  title: "Cookie Policy - Porta-Kamp",
  description: "Porta-Kamp cookie policy. Learn about the cookies we use and how to manage them.",
};

export default function CookiePolicy() {
  return (
    <div className="legal-page">
      <section className="legal-hero">
        <div className="page-hero-grid"></div>
        <div className="page-hero-glow"></div>
        <div className="breadcrumb">
          Home <span>/</span> Cookie Policy
        </div>
        <h1 className="page-title">
          Cookie<br /><em>Policy</em>
        </h1>
        <div className="page-hero-divider"></div>
      </section>

      <section className="legal-content">
        <div className="legal-inner">
          <p className="legal-effective">
            <strong>Effective Date:</strong> 30-Jan-2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> 30-Jan-2025
          </p>

          <h2>What are cookies?</h2>
          <p>
            This Cookie Policy explains what cookies are and how we use them, the types of cookies we
            use i.e, the information we collect using cookies and how that information is used, and how
            to manage the cookie settings.
          </p>
          <p>
            Cookies are small text files that are used to store small pieces of information. They are
            stored on your device when the website is loaded on your browser. These cookies help us
            make the website function properly, make it more secure, provide better user experience,
            and understand how the website performs and to analyze what works and where it needs
            improvement.
          </p>

          <h2>How do we use cookies?</h2>
          <p>
            As most of the online services, our website uses first-party and third-party cookies for
            several purposes. First-party cookies are mostly necessary for the website to function the
            right way, and they do not collect any of your personally identifiable data.
          </p>
          <p>
            The third-party cookies used on our website are mainly for understanding how the website
            performs, how you interact with our website, keeping our services secure, providing
            advertisements that are relevant to you, and all in all providing you with a better and
            improved user experience and help speed up your future interactions with our website.
          </p>

          <h2>Types of Cookies we use</h2>
          <p>
            You can change your cookie preferences any time by visiting cookie settings. This will let
            you revisit the cookie consent banner and change your preferences or withdraw your consent
            right away.
          </p>

          <h2>Managing cookies in your browser</h2>
          <p>
            Different browsers provide different methods to block and delete cookies used by websites.
            You can change the settings of your browser to block/delete the cookies. Listed below are
            the links to the support documents on how to manage and delete cookies from the major web
            browsers:
          </p>
          <ul>
            <li>
              <strong>Chrome:</strong>{" "}
              <a href="https://support.google.com/accounts/answer/32050" target="_blank" rel="noopener noreferrer">
                https://support.google.com/accounts/answer/32050
              </a>
            </li>
            <li>
              <strong>Safari:</strong>{" "}
              <a href="https://support.apple.com/en-in/guide/safari/sfri11471/mac" target="_blank" rel="noopener noreferrer">
                https://support.apple.com/en-in/guide/safari/sfri11471/mac
              </a>
            </li>
            <li>
              <strong>Firefox:</strong>{" "}
              <a href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox" target="_blank" rel="noopener noreferrer">
                https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox
              </a>
            </li>
            <li>
              <strong>Internet Explorer:</strong>{" "}
              <a href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc" target="_blank" rel="noopener noreferrer">
                https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc
              </a>
            </li>
          </ul>
          <p>If you are using any other web browser, please visit your browser&apos;s official support documents.</p>

          <p className="legal-credit">Cookie Policy Generated By CookieYes – Cookie Policy Generator.</p>
        </div>
      </section>
    </div>
  );
}
